version: "3.9"
networks:
  dnd-network:
    external: true
services:
  user-db:
    image: postgres:12-alpine
    container_name: user-db
    ports:
      - "5434:5432"
    networks:
      - dnd-network
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=user-db

  dnd-user-service:
    image: eliriat/dnd-user-service
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: dnd-user-service
    networks:
      - dnd-network
    environment:
      - DB_DRIVER=postgres
      - DB_SOURCE=postgresql://root:secret@user-db:5432/user-db?sslmode=disable
      - SERVER_ADDRESS=0.0.0.0:8080
    depends_on:
      - user-db
    restart: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    entrypoint:
      [
        "/app/wait-for.sh",
        "user-db:5432",
        "--",
        "/app/start.sh"
      ]
    command: ["/app/main"]
