// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"encoding/json"
)

type Character struct {
	ID     int64           `json:"id"`
	Name   string          `json:"name"`
	UserID int64           `json:"user_id"`
	Traits json.RawMessage `json:"traits"`
}

type User struct {
	ID       int64  `json:"id"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}
